// Generated by gencpp from file cartesian_planner/CenterLine.msg
// DO NOT EDIT!


#ifndef CARTESIAN_PLANNER_MESSAGE_CENTERLINE_H
#define CARTESIAN_PLANNER_MESSAGE_CENTERLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cartesian_planner/CenterLinePoint.h>

namespace cartesian_planner
{
template <class ContainerAllocator>
struct CenterLine_
{
  typedef CenterLine_<ContainerAllocator> Type;

  CenterLine_()
    : points()  {
    }
  CenterLine_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cartesian_planner::CenterLinePoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cartesian_planner::CenterLinePoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::cartesian_planner::CenterLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_planner::CenterLine_<ContainerAllocator> const> ConstPtr;

}; // struct CenterLine_

typedef ::cartesian_planner::CenterLine_<std::allocator<void> > CenterLine;

typedef boost::shared_ptr< ::cartesian_planner::CenterLine > CenterLinePtr;
typedef boost::shared_ptr< ::cartesian_planner::CenterLine const> CenterLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_planner::CenterLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_planner::CenterLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_planner::CenterLine_<ContainerAllocator1> & lhs, const ::cartesian_planner::CenterLine_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_planner::CenterLine_<ContainerAllocator1> & lhs, const ::cartesian_planner::CenterLine_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_planner::CenterLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_planner::CenterLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_planner::CenterLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_planner::CenterLine_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_planner::CenterLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_planner::CenterLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_planner::CenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76f98b257c0b7d1218f95661429b5529";
  }

  static const char* value(const ::cartesian_planner::CenterLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76f98b257c0b7d12ULL;
  static const uint64_t static_value2 = 0x18f95661429b5529ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_planner::CenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_planner/CenterLine";
  }

  static const char* value(const ::cartesian_planner::CenterLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_planner::CenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CenterLinePoint[] points\n"
"\n"
"================================================================================\n"
"MSG: cartesian_planner/CenterLinePoint\n"
"float64 s\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"float64 kappa\n"
"float64 left_bound\n"
"float64 right_bound\n"
;
  }

  static const char* value(const ::cartesian_planner::CenterLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_planner::CenterLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CenterLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_planner::CenterLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_planner::CenterLine_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cartesian_planner::CenterLinePoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_PLANNER_MESSAGE_CENTERLINE_H
