// Generated by gencpp from file cartesian_planner/DynamicObstacle.msg
// DO NOT EDIT!


#ifndef CARTESIAN_PLANNER_MESSAGE_DYNAMICOBSTACLE_H
#define CARTESIAN_PLANNER_MESSAGE_DYNAMICOBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>
#include <cartesian_planner/DynamicTrajectoryPoint.h>

namespace cartesian_planner
{
template <class ContainerAllocator>
struct DynamicObstacle_
{
  typedef DynamicObstacle_<ContainerAllocator> Type;

  DynamicObstacle_()
    : polygon()
    , trajectory()  {
    }
  DynamicObstacle_(const ContainerAllocator& _alloc)
    : polygon(_alloc)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _polygon_type;
  _polygon_type polygon;

   typedef std::vector< ::cartesian_planner::DynamicTrajectoryPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cartesian_planner::DynamicTrajectoryPoint_<ContainerAllocator> >::other >  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObstacle_

typedef ::cartesian_planner::DynamicObstacle_<std::allocator<void> > DynamicObstacle;

typedef boost::shared_ptr< ::cartesian_planner::DynamicObstacle > DynamicObstaclePtr;
typedef boost::shared_ptr< ::cartesian_planner::DynamicObstacle const> DynamicObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_planner::DynamicObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_planner::DynamicObstacle_<ContainerAllocator1> & lhs, const ::cartesian_planner::DynamicObstacle_<ContainerAllocator2> & rhs)
{
  return lhs.polygon == rhs.polygon &&
    lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_planner::DynamicObstacle_<ContainerAllocator1> & lhs, const ::cartesian_planner::DynamicObstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cbe4735150eb164552f0f587e68e631";
  }

  static const char* value(const ::cartesian_planner::DynamicObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cbe4735150eb164ULL;
  static const uint64_t static_value2 = 0x552f0f587e68e631ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_planner/DynamicObstacle";
  }

  static const char* value(const ::cartesian_planner::DynamicObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Polygon polygon\n"
"DynamicTrajectoryPoint[] trajectory\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: cartesian_planner/DynamicTrajectoryPoint\n"
"float64 time\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::cartesian_planner::DynamicObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygon);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_planner::DynamicObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_planner::DynamicObstacle_<ContainerAllocator>& v)
  {
    s << indent << "polygon: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.polygon);
    s << indent << "trajectory[]" << std::endl;
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      s << indent << "  trajectory[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cartesian_planner::DynamicTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectory[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_PLANNER_MESSAGE_DYNAMICOBSTACLE_H
